apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: movie-analyst-proxy
  namespace: default
  labels:
    app: movie-analyst-proxy
spec:
  replicas: 3
  minReadySeconds: 45
  selector:
    matchLabels:
      app: movie-analyst-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: movie-analyst-proxy
    spec:
      containers:
        - image: miguelisaza95/movie-analyst-proxy:0.0.1
          imagePullPolicy: IfNotPresent
          name: movie-analyst-proxy
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              memory: 512Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
