apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: movie-analyst-db
  namespace: default
  labels:
    app: movie-analyst-db
spec:
  replicas: 3
  minReadySeconds: 45
  selector:
    matchLabels:
      app: movie-analyst-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: movie-analyst-db
    spec:
      containers:
        - image: ecr_repo/movie-analyst-db:0.0.1
          imagePullPolicy: IfNotPresent
          name: movie-analyst-db
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
